spring:
  application:
    name: commerce-monolith
  datasource:
    # url: jdbc:h2:~/mini-commerce # spring이 직접 process를 잡는 방식
    url: jdbc:h2:tcp://localhost/~/mini-commerce # 이미 띄워져있는 h2에 접근하는 방식
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
